sudo: required
services:
  - docker

before_install:
  # Build a Docker container from the React app (client)
  - docker build -t kinano/multi-container-react-test -f ./client/Dockerfile.dev ./client

script:
  # Run the React app tests and exit
  - docker run kinano/multi-container-react-test npm test -- --coverage

after_success:
  # Build the prd containers
  - docker build -t kinano/multi-container-client ./client
  - docker build -t kinano/multi-container-nginx ./nginx
  - docker build -t kinano/multi-container-server ./server
  - docker build -t kinano/multi-container-worker ./worker
  # Login to Docker CLI
  - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  # Push to Docker hub
  - docker push kinano/multi-container-client
  - docker push kinano/multi-container-server
  - docker push kinano/multi-container-worker
  - docker push kinano/multi-container-nginx
